{{- if .Values.app.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline2.app.fullname" . }}
  labels:
    {{- include "pipeline2.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: port-8000
      protocol: TCP
      name: port-8000
  selector:
    {{- include "pipeline2.app.selectorLabels" . | nindent 4 }}
{{- end }}