{{- if .Values.appdeployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeline2.app-deployment.fullname" . }}
  labels:
    {{- include "pipeline2.app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  {{- with .Values.app.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pipeline2.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pipeline2.app.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9102'
        prometheus.io/path: '/metrics'
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pipeline2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: statsd-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: prom/statsd-exporter:latest
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.app_deployment.envs }}
            {{- toYaml .Values.app_deployment.envs | nindent 12 }}
            {{- end }}
            - name: MINIO_HOST_URL
              value: {{ .Values.config.minio.hostUrl | quote  }}
            - name: MINIO_USE_SSL
              value: {{ .Values.config.minio.useSSL | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.config.minio.accessKey | quote  }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.config.minio.secretKey | quote  }}
            - name: CELERY_BROKER_URL
              value: {{ .Values.config.celery.brokerUrl | quote  }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.config.celery.resultBackend | quote  }}
            - name: LOGSTASH_HOST
              value: {{ .Values.config.logstash.host | quote  }}
            - name: LOGSTASH_PORT
              value: {{ .Values.config.logstash.port | quote  }}
            - name: LOGSTASH_VERSION
              value: {{ .Values.config.logstash.version | quote  }}
            - name: ENV
              value: {{ .Values.config.env | quote  }}
            - name: RELEASE
              value: {{ .Values.config.release | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote  }}
            - name: DASK_RESULTS_BACKEND
              value: {{ .Values.config.daskResultsBackend | quote }}
            {{- if .Values.deployer.enabled }}
            - name: BACKEND_REDIS_HOST
              value: {{ .Values.deployer.redis.host | quote  }}
            - name: BACKEND_REDIS_DB
              value: {{ .Values.deployer.redis.db | quote  }}
            - name: BACKEND_REDIS_PORT
              value: {{ .Values.deployer.redis.port | quote  }}
            - name: DEFAULT_PIPELINE_VERSION
              value: {{ default .Chart.AppVersion .Values.image.version | quote }}
            {{- end }}
            {{- if .Values.app.efs.enabled }}
            - name: EFS_DIRECTORY
              value: {{ default "/efs" .Values.app.efs.efsDir | quote }}
            {{- end }}
          command: {{- toYaml .Values.app.command | nindent 12  }}
          args: {{- toYaml .Values.app.args | nindent 12 }}
          ports:
            - name: port-8000
              containerPort: 8000
          {{- if .Values.app.efs.enabled }}
          volumeMounts:
          - name: app-efs
            mountPath: {{ default "/efs" .Values.app.efs.efsDir | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.app_deployment.resources | nindent 12 }}
      {{- if .Values.app.efs.enabled }}
      volumes:
      - name: app-efs
        persistentVolumeClaim:
          claimName: app-efs
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
