{{- if .Values.deployer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline2.deployer.fullname" . }}
  labels:
    {{- include "pipeline2.deployer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deployer.service.type }}
  ports:
    - port: {{ .Values.deployer.service.port }}
      targetPort: port-8001
      protocol: TCP
      name: port-8001
  selector:
    {{- include "pipeline2.deployer.selectorLabels" . | nindent 4 }}
{{- end }}