{{- if .Values.scheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeline2.scheduler.fullname" . }}
  labels:
    {{- include "pipeline2.scheduler.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.scheduler.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pipeline2.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pipeline2.scheduler.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9102'
        prometheus.io/path: '/metrics'
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pipeline2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - dask-scheduler
            - --port
            - "{{ .Values.scheduler.service.port }}"
            {{- if .Values.scheduler.dashboard.enabled }}
            - --dashboard-address
            - "{{ .Values.scheduler.dashboard.port }}"
            {{- else }}
            - --no-dashboard
            {{- end }}
            {{- if .Values.scheduler.extraArgs }}
              {{- toYaml .Values.scheduler.extraArgs | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8786
            {{- if .Values.scheduler.dashboard.enabled }}
            - containerPort: {{ .Values.scheduler.dashboard.port }}
            {{- end }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          env:
            {{- toYaml .Values.scheduler.env | nindent 12 }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}