{{- if .Values.scheduler.enabled -}}
{{- if .Values.scheduler.ingress.enabled -}}
{{- $fullName := include "pipeline2.scheduler.fullname" . -}}
{{- $svcPort := .Values.scheduler.dashboard.port -}}
{{- $ingressPath := .Values.scheduler.ingress.path -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pipeline2.scheduler.labels" . | nindent 4 }}
  {{- with .Values.scheduler.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.scheduler.ingress.tls }}
  tls:
  {{- range .Values.scheduler.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.scheduler.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{- end }}
{{- end }}
{{- end }}