apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline2.worker.fullname" . }}
  labels:
    {{- include "pipeline2.worker.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8789
    name: port-8789
  clusterIP: None
  selector:
    {{- include "pipeline2.worker.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pipeline2.worker.fullname" . }}
  labels:
    {{- include "pipeline2.worker.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "pipeline2.worker.fullname" . }}
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "pipeline2.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pipeline2.worker.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pipeline2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8789
              name: port-8789
          volumeMounts:
          {{- if .Values.worker.cache.enabled }}
          - name: worker-cache
            mountPath: {{ .Values.worker.cache.tempDir | quote }}
          {{- end }}
          {{- if .Values.worker.efs.enabled }}
          - name: worker-efs
            mountPath: {{ default "/efs" .Values.worker.efs.efsDir | quote }}
          {{- end }}
          env:
            {{ if .Values.worker.envs }}
            {{- toYaml .Values.worker.envs | nindent 12  }}
            {{ end }}
            - name: MINIO_HOST_URL
              value: {{ .Values.config.minio.hostUrl | quote  }}
            - name: MINIO_USE_SSL
              value: {{ .Values.config.minio.useSSL | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.config.minio.accessKey | quote  }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.config.minio.secretKey | quote  }}
            - name: CELERY_BROKER_URL
              value: {{ .Values.config.celery.brokerUrl | quote  }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.config.celery.resultBackend | quote  }}
            - name: LOGSTASH_HOST
              value: {{ .Values.config.logstash.host | quote  }}
            - name: LOGSTASH_PORT
              value: {{ .Values.config.logstash.port | quote  }}
            - name: LOGSTASH_VERSION
              value: {{ .Values.config.logstash.version | quote  }}
            - name: ENV
              value: {{ .Values.config.env | quote  }}
            - name: RELEASE
              value: {{ .Values.config.release | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote  }}
            {{- if .Values.deployer.enabled }}
            - name: BACKEND_REDIS_HOST
              value: {{ .Values.deployer.redis.host | quote  }}
            - name: BACKEND_REDIS_DB
              value: {{ .Values.deployer.redis.db | quote  }}
            - name: BACKEND_REDIS_PORT
              value: {{ .Values.deployer.redis.port | quote  }}
            - name: DEFAULT_PIPELINE_VERSION
              value: {{ default .Chart.AppVersion .Values.image.version | quote }}
            {{- end }}
            {{- if .Values.worker.cache.enabled }}
            - name: DASK__TEMPORARY_DIRECTORY
              value: {{ .Values.worker.cache.tempDir | quote }}
            {{- end }}
            {{- if .Values.worker.efs.enabled }}
            - name: EFS_DIRECTORY
              value: {{ default "/efs" .Values.worker.efs.efsDir | quote }}
            {{- end }}
          command: {{- toYaml .Values.worker.command | nindent 12  }}
          args: {{- toYaml .Values.worker.args | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- if .Values.worker.efs.enabled }}
      volumes:
      - name: worker-efs
        persistentVolumeClaim:
          claimName: worker-efs
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if .Values.worker.cache.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: worker-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.worker.cache.storage.requests | quote  }}
      storageClassName: {{ .Values.worker.cache.storage.className | quote  }}
  {{- end }}
  
