{{- if .Values.worker.efs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.worker.efs.className }}
  csi:
    driver: {{ .Values.worker.efs.driver }}
    volumeHandle: {{ .Values.worker.efs.volumeHandle }}
{{- end }}