{{- if .Values.worker.efs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-efs
spec:
  {{ if .Values.worker.efs.pvc }}
  {{- toYaml .Values.worker.efs.pvc | nindent 2  }}
  {{- end }}
{{- end }}