{{- if .Values.app.efs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-efs-pv
spec:
  {{ if .Values.app.efs.pv }}
  {{- toYaml .Values.app.efs.pv | nindent 2  }}
  {{- end }}
{{- end }}