{{- if .Values.pivottable.ingress.enabled -}}
{{- $fullName := include "previewer.fullname" . -}}
{{- $svcPort := .Values.pivottable.service.port -}}
{{- $ingressPath := .Values.pivottable.ingress.path -}}
{{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.Version) }}
apiVersion: networking.k8s.io/v1
{{- else if  and (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1") (semverCompare "<1.19.0-0" .Capabilities.KubeVersion.Version) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-pivottable
  labels:
    {{- include "previewer.labels" . | nindent 4 }}
  {{- with .Values.pivottable.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.pivottable.ingress.tls }}
  tls:
  {{- range .Values.pivottable.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.pivottable.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if and ($.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">=1.19.0-0" $.Capabilities.KubeVersion.Version)}}
            pathType: Prefix
            {{- end }} 
            backend:
              {{- if and ($.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">=1.19.0-0" $.Capabilities.KubeVersion.Version)}}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else}} 
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end}}
  {{- end }}
{{- end }}