{{- if .Values.pivottable.torage.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pivottable-cache
 labels:
   app: previewer
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: {{ .Values.pivottable.storage.requests | quote  }}
 storageClassName: {{ .Values.pivottable.storage.className | quote  }}
{{- end }}