apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: api-uploads
 labels:
   app: api
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: {{ .Values.storage.requests | quote  }}
 storageClassName: {{ .Values.storage.className | quote  }}